name: Run Tests and Post Results

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      toxdeps: tox-conda
      pytest: true
      pytest-results-summary: true
      coverage: codecov
      envs: |
        - linux: py312-cov
          coverage: codecov
          pytest-results-summary: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}