name: Post Test Results to PR

on:
  workflow_run:
    workflows: ["Run Tests with OpenAstronomy"]
    types:
      - completed

jobs:
  post-results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped' && github.event.workflow_run.event == 'pull_request'
    
    steps:
      - name: Download test results artifact
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            
            const testResultsArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === "test-results"
            );
            
            if (!testResultsArtifact) {
              console.log("No test results artifact found");
              return;
            }
            
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: testResultsArtifact.id,
              archive_format: 'zip'
            });
            
            const fs = require('fs');
            fs.writeFileSync('test-results.zip', Buffer.from(download.data));
            
      - name: Extract test results
        if: success()
        run: |
          unzip -o test-results.zip
          if [ -f "pytest-results.txt" ]; then
            echo "TEST_RESULTS_FOUND=true" >> $GITHUB_ENV
            # Limit the size to avoid exceeding GitHub comment limits
            head -n 500 pytest-results.txt > test-summary.txt
          else
            echo "No pytest-results.txt file found"
          fi
      
      - name: Find PR number
        if: env.TEST_RESULTS_FOUND == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const payload = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            
            const prNumberMatch = payload.data.head_branch.match(/refs\/pull\/(\d+)\/merge/);
            if (!prNumberMatch) {
              console.log("Could not extract PR number");
              return;
            }
            
            const prNumber = prNumberMatch[1];
            core.exportVariable('PR_NUMBER', prNumber);
      
      - name: Post test results to PR
        if: env.TEST_RESULTS_FOUND == 'true' && env.PR_NUMBER != ''
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const testResults = fs.readFileSync('test-summary.txt', 'utf8');
            
            const body = `## Pytest Results
            \`\`\`
            ${testResults}
            \`\`\`
            
            [View full test results in the workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER,
              body
            });