name: Run Unit Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run unit tests with coverage
        run: pytest --cov=. --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./
          fail_ci_if_error: true
          files: ./coverage.xml
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
